<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "certificate_tariffcodes".
 *
 * @property integer $id_certificate_tariffcode
 * @property integer $id_certificate
 * @property integer $id_tariffcodes_class
 * @property integer $id_tariffcodes_category
 * @property integer $id_tariffcodes_product
 * @property integer $id_country
 * @property string $created
 * @property string $modified
 * @property string $code_tariffcodes_class
 * @property string $code_tariffcodes_category
 * @property string $code_tariffcodes_product
 * @property string $code
 * @property string $desc_tariffcodes_class
 * @property string $desc_tariffcodes_category
 * @property string $desc_tariffcodes_product
 * @property string $description
 * @property string $value
 * @property string $qty
 * @property string $weight
 *
 * @property \common\models\TariffcodesClass $codeTariffcodesClass
 * @property \common\models\TariffcodesCategory $codeTariffcodesCategory
 * @property \common\models\TariffcodesProduct $codeTariffcodesProduct
 * @property \common\models\Certificate $certificate
 * @property \common\models\TariffcodesClass $tariffcodesClass
 * @property \common\models\TariffcodesCategory $tariffcodesCategory
 * @property \common\models\Country $country
 * @property string $aliasModel
 */
abstract class CertificateTariffcodes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'certificate_tariffcodes';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_certificate', 'id_country', 'code_tariffcodes_class', 'code_tariffcodes_category', 'code_tariffcodes_product', 'description', 'value', 'qty', 'weight'], 'required'],//'created', 'modified',
            [['id_certificate', 'id_tariffcodes_class', 'id_tariffcodes_category', 'id_tariffcodes_product'], 'integer'],
            //[['created', 'modified'], 'safe'],
            [['value', 'qty', 'weight'], 'number'],
            [['code_tariffcodes_class', 'code_tariffcodes_category', 'id_country'], 'string', 'max' => 2],
            [['code_tariffcodes_product'], 'string', 'max' => 4],
            [['code'], 'string', 'max' => 8],
            [['desc_tariffcodes_class', 'desc_tariffcodes_category', 'desc_tariffcodes_product', 'description'], 'string', 'max' => 255],
            [['code_tariffcodes_class'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TariffcodesClass::className(), 'targetAttribute' => ['code_tariffcodes_class' => 'code']],
            [['code_tariffcodes_category'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TariffcodesCategory::className(), 'targetAttribute' => ['code_tariffcodes_category' => 'code']],
            [['code_tariffcodes_product'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TariffcodesProduct::className(), 'targetAttribute' => ['code_tariffcodes_product' => 'code']],
            [['id_certificate'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Certificate::className(), 'targetAttribute' => ['id_certificate' => 'id_certificate']],
            [['id_tariffcodes_class'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TariffcodesClass::className(), 'targetAttribute' => ['id_tariffcodes_class' => 'id_tariffcodes_class']],
            [['id_tariffcodes_category'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TariffcodesCategory::className(), 'targetAttribute' => ['id_tariffcodes_category' => 'id_tariffcodes_category']],
            [['id_country'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Country::className(), 'targetAttribute' => ['id_country' => 'cca2']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_certificate_tariffcode' => Yii::t('models', 'Id Certificate Tariffcode'),
            'id_certificate' => Yii::t('models', 'Id Certificate'),
            'id_tariffcodes_class' => Yii::t('models', 'Id Tariffcodes Class'),
            'id_tariffcodes_category' => Yii::t('models', 'Id Tariffcodes Category'),
            'id_tariffcodes_product' => Yii::t('models', 'Id Tariffcodes Product'),
            'id_country' => Yii::t('models', 'Id Country'),
            'created' => Yii::t('models', 'Created'),
            'modified' => Yii::t('models', 'Modified'),
            'code_tariffcodes_class' => Yii::t('models', 'Code Tariffcodes Class'),
            'code_tariffcodes_category' => Yii::t('models', 'Code Tariffcodes Category'),
            'code_tariffcodes_product' => Yii::t('models', 'Code Tariffcodes Product'),
            'code' => Yii::t('models', 'Code'),
            'desc_tariffcodes_class' => Yii::t('models', 'Desc Tariffcodes Class'),
            'desc_tariffcodes_category' => Yii::t('models', 'Desc Tariffcodes Category'),
            'desc_tariffcodes_product' => Yii::t('models', 'Desc Tariffcodes Product'),
            'description' => Yii::t('models', 'Description'),
            'value' => Yii::t('models', 'Value'),
            'qty' => Yii::t('models', 'Qty'),
            'weight' => Yii::t('models', 'Weight'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCodeTariffcodesClass()
    {
        return $this->hasOne(\common\models\TariffcodesClass::className(), ['code' => 'code_tariffcodes_class']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCodeTariffcodesCategory()
    {
        return $this->hasOne(\common\models\TariffcodesCategory::className(), ['code' => 'code_tariffcodes_category']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCodeTariffcodesProduct()
    {
        return $this->hasOne(\common\models\TariffcodesProduct::className(), ['code' => 'code_tariffcodes_product']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificate()
    {
        return $this->hasOne(\common\models\Certificate::className(), ['id_certificate' => 'id_certificate']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTariffcodesClass()
    {
        return $this->hasOne(\common\models\TariffcodesClass::className(), ['id_tariffcodes_class' => 'id_tariffcodes_class']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTariffcodesCategory()
    {
        return $this->hasOne(\common\models\TariffcodesCategory::className(), ['id_tariffcodes_category' => 'id_tariffcodes_category']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountry()
    {
        return $this->hasOne(\common\models\Country::className(), ['cca2' => 'id_country']);
    }




}
