<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "certificate_guichet".
 *
 * @property integer $id_certificate_guichet
 * @property integer $id_certificate
 * @property string $created
 * @property string $modified
 * @property string $di
 * @property string $pr_nr
 * @property string $statistic_nr
 *
 * @property \common\models\Certificate $idCertificate
 * @property string $aliasModel
 */
abstract class CertificateGuichet extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'certificate_guichet';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_certificate', 'di', 'pr_nr','statistic_nr'], 'required'],
            [['id_certificate'], 'integer'],
            [['created', 'modified'], 'safe'],
            [['di'], 'string', 'max' => 20],
            [['pr_nr','statistic_nr'], 'string', 'max' => 50],
            [['id_certificate'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Certificate::className(), 'targetAttribute' => ['id_certificate' => 'id_certificate']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_certificate_guichet' => Yii::t('models', 'Id Certificate Guichet'),
            'id_certificate' => Yii::t('models', 'Id Certificate'),
            'created' => Yii::t('models', 'Created'),
            'modified' => Yii::t('models', 'Modified'),
            'di' => Yii::t('models', 'DI/SGS'),
            'pr_nr' => Yii::t('models', 'PR NR'),
            'statistic_nr' => Yii::t('models', 'Statistical NIF Number'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCertificate()
    {
        return $this->hasOne(\common\models\Certificate::className(), ['id_certificate' => 'id_certificate']);
    }



    /**
     * @inheritdoc
     * @return \common\models\query\CertificateGuichetQuery the active query used by this AR class.
     */
    /*public static function find()
    {
        return new \common\models\query\CertificateGuichetQuery(get_called_class());
    }*/


}
