<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "city".
 *
 * @property integer $id_city_cache
 * @property string $created
 * @property string $modified
 * @property string $name
 */
abstract class CityCache extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'city_cache';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['q', 'feature_code', 'country_code', 'results'], 'required'],
            [['created', 'modified'], 'safe'],
            [['q'], 'string', 'max' => 30],
            [['country_code'], 'string', 'max' => 2],
            [['feature_code'], 'string', 'max' => 255],
            [['results'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'q' => Yii::t('models', 'Query'),
            'created' => Yii::t('models', 'Created'),
            'modified' => Yii::t('models', 'Modified'),
            'country_code' => Yii::t('models', 'Country Code ISO2'),
            'results' => Yii::t('models', 'Results'),
        ];
    }

    /**
     * @inheritdoc
     * @return \common\models\query\CityQuery the active query used by this AR class.
     */
    /*public static function find()
    {
        return new \common\models\query\CityQuery(get_called_class());
    }*/


}
