<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "country".
 *
 * @property integer $id_country
 * @property string $name
 * @property string $name_common
 * @property string $name_official
 * @property string $name_native_common
 * @property string $name_native_official
 * @property string $tld
 * @property string $cca2
 * @property string $ccn3
 * @property string $cca3
 * @property string $currency
 * @property string $callingCode
 * @property string $capital
 * @property string $altSpellings
 * @property string $relevance
 * @property string $continent
 * @property string $region
 * @property string $subregion
 * @property string $nativeLanguage
 * @property string $languages
 * @property string $translations
 * @property string $latlng
 * @property string $demonym
 * @property string $borders
 * @property string $area
 *
 * @property \common\models\Certificate[] $certificates
 * @property \common\models\Certificate[] $certificates0
 * @property \common\models\Certificate[] $certificates1
 * @property \common\models\Certificate[] $certificates2
 * @property \common\models\CertificateTranshipment[] $certificateTranshipments
 * @property \common\models\Harbor[] $harbors
 * @property \common\models\User[] $users
 * @property string $aliasModel
 */
abstract class Country extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'country';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'name_common', 'name_official', 'name_native_common', 'name_native_official', 'tld', 'cca2', 'ccn3', 'cca3', 'currency', 'callingCode', 'capital', 'altSpellings', 'relevance', 'continent', 'region', 'subregion', 'nativeLanguage', 'languages', 'translations', 'latlng', 'demonym', 'borders', 'area'], 'required'],
            [['name', 'name_common', 'name_official', 'name_native_common', 'name_native_official', 'currency', 'callingCode', 'capital', 'altSpellings', 'relevance', 'region', 'subregion', 'nativeLanguage', 'languages', 'translations', 'latlng', 'demonym', 'borders', 'area'], 'string', 'max' => 255],
            [['tld'], 'string', 'max' => 10],
            [['cca2'], 'string', 'max' => 2],
            [['ccn3', 'cca3'], 'string', 'max' => 3],
            [['continent'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_country' => Yii::t('models', 'Id Country'),
            'name' => Yii::t('models', 'Name'),
            'name_common' => Yii::t('models', 'Name Common'),
            'name_official' => Yii::t('models', 'Name Official'),
            'name_native_common' => Yii::t('models', 'Name Native Common'),
            'name_native_official' => Yii::t('models', 'Name Native Official'),
            'tld' => Yii::t('models', 'Tld'),
            'cca2' => Yii::t('models', 'Cca2'),
            'ccn3' => Yii::t('models', 'Ccn3'),
            'cca3' => Yii::t('models', 'Cca3'),
            'currency' => Yii::t('models', 'Currency'),
            'callingCode' => Yii::t('models', 'Calling Code'),
            'capital' => Yii::t('models', 'Capital'),
            'altSpellings' => Yii::t('models', 'Alt Spellings'),
            'relevance' => Yii::t('models', 'Relevance'),
            'continent' => Yii::t('models', 'Continent'),
            'region' => Yii::t('models', 'Region'),
            'subregion' => Yii::t('models', 'Subregion'),
            'nativeLanguage' => Yii::t('models', 'Native Language'),
            'languages' => Yii::t('models', 'Languages'),
            'translations' => Yii::t('models', 'Translations'),
            'latlng' => Yii::t('models', 'Latlng'),
            'demonym' => Yii::t('models', 'Demonym'),
            'borders' => Yii::t('models', 'Borders'),
            'area' => Yii::t('models', 'Area'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificates()
    {
        return $this->hasMany(\common\models\Certificate::className(), ['goods_loading_id_country' => 'id_country']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function CertificatesImporter()
    {
        return $this->hasMany(\common\models\Certificate::className(), ['goods_origin_id_country' => 'id_country']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificates1()
    {
        return $this->hasMany(\common\models\Certificate::className(), ['exporter_id_country' => 'id_country']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificates2()
    {
        return $this->hasMany(\common\models\Certificate::className(), ['importer_id_country' => 'id_country']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificateTranshipments()
    {
        return $this->hasMany(\common\models\CertificateTranshipment::className(), ['id_country' => 'id_country']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHarbors()
    {
        return $this->hasMany(\common\models\Harbor::className(), ['id_country' => 'id_country']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(\common\models\User::className(), ['id_countries' => 'id_country']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificateTariffcodes()
    {
        return $this->hasMany(\common\models\CertificateTariffcodes::className(), ['id_country' => 'id_country']);
    }

}
