<?php

// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "doc".
 *
 * @property integer $id_doc
 * @property string $created
 * @property string $modified
 * @property string $name
 * @property string $path
 */
abstract class Doc extends \yii\db\ActiveRecord {
    public $upload_bill_lading;
    public $upload_commercial_invoice;
    public $upload_freight_invoice;
    public $upload_draft_request_signed;
    public $upload_other;
    public $upload_certificate;
    public $upload_du;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'doc';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['name', 'path'], 'required'],
            [['id_doc'], 'integer'],
            [['created', 'modified'], 'safe'],
            [['name', 'path'], 'string', 'max' => 255],
            [['id_doc'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Doc::className(), 'targetAttribute' => ['id_doc' => 'id_doc']],
            //[['upload_bill_lading'], 'file', 'skipOnEmpty' => true, 'extensions' => ['png', 'jpg', 'gif', 'pdf'], 'maxSize' => 1024*1024, 'message' => 'This file in'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id_doc' => Yii::t('models', 'Document Id'),
            'created' => Yii::t('models', 'Created'),
            'modified' => Yii::t('models', 'Modified'),
            'name' => Yii::t('models', 'Name'),
            'path' => Yii::t('models', 'Path'),
            'upload_bill_lading' => Yii::t('models', 'Document - Bill of Lading Document'),
        ];
    }

    /**
     * uploads
     */
    public function uploads($doc) {
        if ( $this->validate()){
            $this->upload_bill_lading = UploadedFile::getInstance($doc, 'upload_bill_lading');
            $fileName = 'docs/' .$this->upload_bill_lading->baseName . '.' . $this->upload_bill_lading->extension;
            $fileName = preg_replace('/\s+/', '', $fileName);
            $this->path = $fileName;
            $this->name = $fileName;
            $this->save();
            $this->upload_bill_lading->saveAs($filename);
            return true;
        } else {
            return false;
        }
    }
}
