<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "harbor".
 *
 * @property integer $id_harbor
 * @property integer $id_country
 * @property string $created
 * @property string $modified
 * @property string $name
 *
 * @property \common\models\Certificate[] $certificates
 * @property \common\models\Certificate[] $certificates0
 * @property \common\models\CertificateTranshipment[] $certificateTranshipments
 * @property \common\models\Country $idCountry
 * @property string $aliasModel
 */
abstract class Harbor extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'harbor';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_country', 'created', 'name'], 'required'],
            [['id_country'], 'integer'],
            [['created', 'modified'], 'safe'],
            [['name'], 'string', 'max' => 50],
            [['id_country'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Country::className(), 'targetAttribute' => ['id_country' => 'id_country']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_harbor' => Yii::t('models', 'Id Harbor'),
            'id_country' => Yii::t('models', 'Id Country'),
            'created' => Yii::t('models', 'Created'),
            'modified' => Yii::t('models', 'Modified'),
            'name' => Yii::t('models', 'Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificatesGoodsLoadingHarbor()
    {
        return $this->hasMany(\common\models\Certificate::className(), ['goods_loading_id_harbor' => 'id_harbor']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificatesGoodsOriginHarbor()
    {
        return $this->hasMany(\common\models\Certificate::className(), ['goods_origin_id_harbor' => 'id_harbor']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificateTranshipments()
    {
        return $this->hasMany(\common\models\CertificateTranshipment::className(), ['id_harbor' => 'id_harbor']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCountry()
    {
        return $this->hasOne(\common\models\Country::className(), ['id_country' => 'id_country']);
    }



    /**
     * @inheritdoc
     * @return \common\models\query\HarborQuery the active query used by this AR class.
     */
    /*public static function find()
    {
        return new \common\models\query\HarborQuery(get_called_class());
    }*/


}
