<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the base-model class for table "invoices_certificates".
 *
 * @property integer $id_invoice
 * @property integer $id_certificate
 * @property string $created
 * @property integer $status
 * @property string $obs
 * @property string $total
 *
 * @property \common\models\Invoices $idInvoice
 * @property \common\models\Certificate $idCertificate
 * @property string $aliasModel
 */
abstract class InvoicesCertificates extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created', 'modified'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['modified'],
                ],
                'value' => new Expression('NOW()'),
            ],
        ];
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoices_certificates';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_invoice', 'id_certificate'], 'required'],
            [['id_invoice', 'id_certificate'], 'integer'],
            [['created'], 'safe'],
            [['id_invoice'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Invoices::className(), 'targetAttribute' => ['id_invoice' => 'id_invoice']],
            [['id_certificate'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Certificate::className(), 'targetAttribute' => ['id_certificate' => 'id_certificate']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_invoice' => Yii::t('models', 'Id Invoice'),
            'id_certificate' => Yii::t('models', 'Id Certificate'),
            'created' => Yii::t('models', 'Created'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoice()
    {
        return $this->hasOne(\common\models\Invoices::className(), ['id_invoice' => 'id_invoice']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificate()
    {
        return $this->hasOne(\common\models\Certificate::className(), ['id_certificate' => 'id_certificate']);
    }

}
