<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "tariffcodes_product".
 *
 * @property integer $id_tariffcodes_product
 * @property integer $id_category
 * @property string $code
 * @property string $description_en
 * @property string $description_pt
 *
 * @property \common\models\CertificateTariffcodes[] $certificateTariffcodes
 * @property \common\models\TariffcodesCategory $category
 * @property string $aliasModel
 */
abstract class TariffcodesProduct extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tariffcodes_product';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_category', 'code', 'description_en', 'description_pt'], 'required'],
            [['id_category'], 'integer'],
            [['code'], 'string', 'max' => 4],
            [['description_en', 'description_pt'], 'string', 'max' => 255],
            [['id_category'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TariffcodesCategory::className(), 'targetAttribute' => ['id_category' => 'id_tariffcodes_category']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_tariffcodes_product' => Yii::t('models', 'Id Tariffcodes Product'),
            'id_category' => Yii::t('models', 'Id Category'),
            'code' => Yii::t('models', 'Code'),
            'description_en' => Yii::t('models', 'Description En'),
            'description_pt' => Yii::t('models', 'Description Pt'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificateTariffcodes()
    {
        return $this->hasMany(\common\models\CertificateTariffcodes::className(), ['code_tariffcodes_product' => 'code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\TariffcodesCategory::className(), ['id_tariffcodes_category' => 'id_category']);
    }




}
