<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "tariffcodes_class".
 *
 * @property integer $id_tariffcodes_class
 * @property string $code
 * @property string $description_en
 * @property string $description_pt
 *
 * @property \common\models\CertificateTariffcodes[] $certificateTariffcodes
 * @property \common\models\CertificateTariffcodes[] $certificateTariffcodes0
 * @property \common\models\TariffcodesCategory[] $tariffcodesCategories
 * @property string $aliasModel
 */
abstract class TariffcodesClass extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tariffcodes_class';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'description_en', 'description_pt'], 'required'],
            [['code'], 'string', 'max' => 2],
            [['description_en', 'description_pt'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_tariffcodes_class' => Yii::t('models', 'Id Tariffcodes Class'),
            'code' => Yii::t('models', 'Code'),
            'description_en' => Yii::t('models', 'Description En'),
            'description_pt' => Yii::t('models', 'Description Pt'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificateTariffcodes()
    {
        return $this->hasMany(\common\models\CertificateTariffcodes::className(), ['code_tariffcodes_class' => 'code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertificateTariffcodes0()
    {
        return $this->hasMany(\common\models\CertificateTariffcodes::className(), ['id_tariffcodes_class' => 'id_tariffcodes_class']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTariffcodesCategories()
    {
        return $this->hasMany(\common\models\TariffcodesCategory::className(), ['id_class' => 'id_tariffcodes_class']);
    }




}
