<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '1-EURO; 2-DOLAR' => '',
    'Cost Baf Value' => '',
    'Cost Caf Value' => '',
    'Cost Extracharges Value' => '',
    'Cost Fob Value' => '',
    'Cost Insurance Value' => '',
    'Cost Invoice Value' => '',
    'Cost Oceanfreight Value' => '',
    'Cost Thc Value' => '',
    'Created' => '',
    'Docs Bill Lading' => '',
    'Docs Commercial Invoice' => '',
    'Docs Freight Invoice' => '',
    'Exporter Address' => '',
    'Exporter Email' => '',
    'Exporter Id City' => '',
    'Exporter Id Country' => '',
    'Exporter Name' => '',
    'Exporter Phone' => '',
    'Goods Description' => '',
    'Goods Imgcode' => '',
    'Goods Loading Id Country' => '',
    'Goods Loading Id Harbor' => '',
    'Goods Origin Id Country' => '',
    'Goods Origin Id Harbor' => '',
    'Guichet Pr Nr' => '',
    'Guichet Statistic Nr' => '',
    'Id Certificate' => '',
    'Id Product Type' => '',
    'Id User Client' => '',
    'Id User Invoicer' => '',
    'Id User Maker' => '',
    'Importer Address' => '',
    'Importer Email' => '',
    'Importer Id City' => '',
    'Importer Id Country' => '',
    'Importer Name' => '',
    'Importer Phone' => '',
    'Lading 20ft Nr' => '',
    'Lading 40ft Nr' => '',
    'Lading Chassis Nr' => '',
    'Lading Packages Nr' => '',
    'Lading Volume' => '',
    'Lading Weight' => '',
    'Modified' => '',
    'Price' => '',
    'Vessel Bl Nr' => '',
    'Vessel Incoterm' => '',
    'Vessel Loading Date' => '',
    'Vessel Name' => '',
    'Vessel Shipping Line' => '',
    'Vessel Voyage Nr' => '',
];
